name: Multicorn
description: Unified data access library
license: GPLv3
public: true
url: http://www.multicorn.org/

menu:
  - Overview:
      link: /
  - Demo:
      link: http://trymulticorn.org/
  - FDW Documentation:
      link: /foreign-data-wrappers
  - Issues:
      link: http://redmine.kozea.fr/projects/multicorn/issues

vcs (git):
  url: git://github.com/Kozea/Multicorn.git
  path: /var/db/git/multicorn.git

code browser (github):
  project name: Kozea/Multicorn

bug tracker (redmine):
  base url: http://redmine.kozea.fr/
  project name: multicorn

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: Multicorn
