name: Multicorn
description: Unified data access library
license: GPLv3
public: true
url: http://www.multicorn.org/

menu:
  - Overview:
      link: /
  - News:
      link: /news/
  - Documentation:
      link: /documentation/
  - Contribute:
      link: /contribute/
  - Issues:
      link: https://github.com/Kozea/Multicorn/issues

project (git):
  url: git://github.com/Kozea/Multicorn.git
  path: multicorn

vcs (git):
  url: git://github.com/Kozea/Multicorn.git
  path: /var/db/git/multicorn.git

code browser (github):
  project name: Kozea/Multicorn

bug tracker (github):
  project name: Kozea/Multicorn

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: Multicorn

mailing list (librelist):
  project name: multicorn
